# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mesos-master" do |master|
    master.vm.box = "centos/7"
    master.vm.network "private_network", ip: "10.111.111.10"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "mesos-master"
      vb.memory = "1024"
    end
    master.vm.provision "shell", path: "master.sh"
  end

  config.vm.define "mesos-agent1" do |agent|
    agent.vm.box = "centos/7"
    agent.vm.network "private_network", ip: "10.111.111.11"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "mesos-agent1"
      vb.memory = "1024"
    end
    agent.vm.provision "shell", path: "agent.sh"
  end

  config.vm.define "mesos-agent2" do |agent|
    agent.vm.box = "centos/7"
    agent.vm.network "private_network", ip: "10.111.111.12"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "mesos-agent2"
      vb.memory = "1024"
    end
    agent.vm.provision "shell", path: "agent.sh"
  end

end
