# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mesos-master" do |master|
    master.vm.box = "centos/7"
    master.vm.network "private_network", ip: "10.111.111.10"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "mesos-master"
      vb.memory = "1024"
      vb.cpus = "1"
    end
    master.vm.provision "file", source: "start-kafka.sh", destination: "/home/vagrant/start-kafka.sh"
    master.vm.provision "file", source: "config.json", destination: "/home/vagrant/config.json"
    master.vm.provision "file", source: "nginx.json", destination: "/home/vagrant/nginx.json"
    master.vm.provision "shell", path: "master.sh"
  end

  agents = [1, 2]

  agents.each do | agentNumber |
    config.vm.define "mesos-agent#{agentNumber}" do |agent|
      agent.vm.box = "centos/7"
      agent.vm.network "private_network", ip: "10.111.111.1#{agentNumber}"
      agent.vm.provider "virtualbox" do |vb|
        vb.name = "mesos-agent#{agentNumber}"
        vb.memory = "8192"
        vb.cpus = "4"
      end
      agent.vm.provision "shell", path: "agent.sh", env: {"VAGRANT_IP" => "10.111.111.1#{agentNumber}"}
    end
  end
end
